replicaCount: 1

image:
  repository: ilyaratko/podmanager
  tag: "1.1.1"

# redisImage: "r-int.hyperion.mos.ru/redis:7.0-alpine"
redisImage: "redis:7.0-alpine"


ingress:
  host: "podmanager.local"

env:
  freeStacksCount: 3
  maxStacksCount: 5
  configFile: "/app/kubeconfig"
  namespace: "default"
  ueMainImage: "hashicorp/http-echo"
  ueSignalingImage: "jmalloc/echo-server"
  ueSignalingPort: 8080
  baseUrl: "wss://signaling.meta.mos.ru/"
  UE_Signaling_Container_Port: 80
