replicaCount: 1

image:
  repository: ilyaratko/podmanager
  tag: "latest"

# redisImage: "r-int.hyperion.mos.ru/redis:7.0-alpine"
redisImage: "redis:7.0-alpine"


ingress:
  host: "podmanager.local"

env:
  baseUrl: "https://meta2.mos.ru/"
  freeStacksCount: 3
  maxStacksCount: 5
  configFile: "/app/token.json"
  namespace: "default"
  ueMainImage: "hashicorp/http-echo"
  ueSignalingImage: "jmalloc/echo-server"
  ueSignalingPort: 8080
