apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-env
data:
  .env: |
    BASE_URL={{ .Values.env.baseUrl }}
    K8S_FREE_STACKS_COUNT={{ .Values.env.freeStacksCount }}
    K8S_MAX_STACKS_COUNT={{ .Values.env.maxStacksCount }}
    K8S_CONFIG_FILE={{ .Values.env.configFile }}
    K8S_NAMESPACE={{ .Values.env.namespace }}
    UE_MAIN_IMAGE={{ .Values.env.ueMainImage }}
    UE_SIGNALING_IMAGE={{ .Values.env.ueSignalingImage }}
    UE_SIGNALING_PORT={{ .Values.env.ueSignalingPort }}
    UE_SIGNALING_CONTAINER_PORT={{ .Values.env.UE_Signaling_Container_Port }}
