apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - name: podmanager
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["uvicorn", "podmanager.main:app", "--host", "0.0.0.0", "--port", "8000"]
        env:
        - name: SERVICE_CODE
          value: podmanager
        - name: REDIS_DSN
          value: redis://localhost
        livenessProbe:
          tcpSocket:
            port: 8000
        readinessProbe:
          tcpSocket:
            port: 8000
        volumeMounts:
        - name: env
          mountPath: /app/.env
          subPath: .env
      - name: background-tasks
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["saq", "podmanager.background_tasks.settings.background_task_settings", "--web"]
        env:
        - name: SERVICE_CODE
          value: background_tasks
        - name: REDIS_DSN
          value: redis://localhost
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: env
          mountPath: /app/.env
          subPath: .env
      - name: redis
        image: {{ .Values.redisImage }}
        ports:
        - containerPort: 6379
      volumes:
      - name: env
        configMap:
          name: {{ .Chart.Name }}-env
