apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:

spec:
  ingressClassName: citrix
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 8000
      - path: /tasks
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}
            port:
              number: 8080
