apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: {{ .Chart.Name }}-metrics
    port: 28080
    protocol: TCP
    targetPort: 28080
  - name: {{ .Chart.Name }}-0
    port: 8000
    protocol: TCP
  - name: back-tasks-0
    port: 8080
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}
  type: ClusterIP
